# 服务端口
server:
  port: 8003

# Spring 配置
spring:
  application:
    name: service-user
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev

# Mybatis Plus
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-aliases-package: com.yunji.yj.service.entity.*
#  global-config:
#    db-config:
#      id-type: id_worker
#      insert-strategy: not_null
#      update-strategy: not_null
#      select-strategy: not_empty
#      table-underline: true
#      capital-mode: true
#  type-handlers-package: com.yunji.yj.service.type
#  configuration:
#    jdbc-type-for-null: null
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Swagger 配置
swagger:
  enabled: true
  title: Microservice 用户服务-在线接口文档
  description: Microservice 用户服务-在线接口文档
  version: 1.0.1
  termsOfServiceUrl: https://www.lmaye.com
  basePackage: com.lmaye.ms.service.user.controller
  basePath: /**
  contact:
    email: lmay@lmaye.com
    name: lmay Zhou
    url: https://www.lmaye.com
  globalOperationParameters:
    - description: 凭证
      modelRef: string
      name: Authorization
      parameterType: header
      required: false
