# Spring 配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Mybatis Plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.lmaye.ms.*.entity.*
  global-config:
    db-config:
      id-type: ASSIGN_ID
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      table-underline: true
      capital-mode: true
  type-handlers-package: com.lmaye.cloud.starter.mybatis.type
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Swagger 配置
springfox:
  documentation:
    enabled: true
swagger:
  title: Microservice API-在线接口文档
  description: LmayE Software, Inc.
  version: 1.0.1
  termsOfServiceUrl: https://www.lmaye.com
  basePackage: com.lmaye.ms
  basePath: /**
  excludePath: /error
  contact:
    email: lmay@lmaye.com
    name: lmay Zhou
    url: https://www.lmaye.com
  global-operation-parameters:
    - description: 凭证
      modelRef: string
      name: Authorization
      parameterType: header
      required: true

# 资源客户端, 访问放行路径
security:
  oauth2:
    resource:
      ignore-uris:
        - /doc.html
        - /swagger-ui.html
        - /v2/api-docs
        - /swagger-resources
        - /swagger-resources/configuration/**
        - /webjars/**
        - /v3/api-docs
        - /swagger-ui/**
        - /actuator/**
        - /instances/**
        - /run
        # 认证查询用户接口
        - /user/queryByUserName/*

# 日志
logging:
  config: classpath:log4j2-@profile.active@.xml