spring:
  # 数据库配置
  datasource:
    name: sys
    url: jdbc:mysql://172.31.6.106:3306/ms_user?allowMultiQueries=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    hikari:
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 2
      connection-timeout: 30000
      idle-timeout: 30000
      connection-test-query: select 1
  cloud:
    # Nacos 注册中心
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 172.31.6.106:8848
        namespace: a6b8fdfd-14b4-4264-94fc-9d41b92a7035

# MinIO File Store
minio:
  store:
    endpoint: http://172.31.6.106:9000
    bucket: ms-example
    accessKey: minio
    secretKey: minio123
    partMaxSize: 10485760
    cleanCache:
      enabled: true
      directory: ./tmp
      cleanPeriod: 12960000
      aliveDuration: 12960000

# 日志
logging:
  config: classpath:log4j2-dev.xml
