# 服务端口
server:
  port: 8002

spring:
  # 数据库配置
  datasource:
    name: sys
    url: jdbc:mysql://${MYSQL_HOST:lms-mysql}:${MYSQL_PORT:3306}/ms_user?allowMultiQueries=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    hikari:
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 2
      connection-timeout: 30000
      idle-timeout: 30000
      connection-test-query: select 1
  # Redis
  redis:
    host: ${REDIS_HOST:lms-redis}
    port: ${REDIS_PORT:6379}
    database: 1
    password: 123456
    timeout: 1000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
#  session:
#    store-type: redis

# 项目配置
oauth:
  cookieDomain: localhost
  cookieMaxAge: -1
  defaultTokenUrl: http://127.0.0.1:8002/oauth/token

encrypt:
  key-store:
    # 证书路径
    location: classpath:/ms-service-oauth.jks
    # 秘钥
    secret: ms-oauth
    # 别名
    alias: ms-service-oauth
    # 证书密码
    password: ms-oauth
