# 服务端口
server:
  port: 80

# Spring 配置
spring:
  # Redis
  redis:
    host: ${REDIS_HOST:lms-redis}
    port: 6379
    password: 123456
    timeout: 100ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    # 网关
    gateway:
      globalcors:
        cors-configurations:
          # 匹配所有请求
          '[/**]':
            # 跨域处理 允许所有的域
            allowedOrigins: "*"
            # 支持的方法
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      # 路由
      routes:
        - id: user-service-route
#          uri: http://localhost:8003
          uri: lb://user-service
          predicates:
#            - Host = test.lmaye.com**
            - Path=/**
          filters:
#            - PrefixPath=/user
            - StripPrefix=1

# 网关认证配置
gateway-auth:
  # Token 标识
  authorizeToken: Authorization
  # 放行的请求路径(eg: /api/shopify-plugin/category/list)
  excludeUrls:
    - /*/doc.html
    - /*/v3/api-docs
    - /**/doc.html
    - /**/swagger-resources
    - /**/swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /**/webjars/springfox-swagger-ui/**
  # 认证登录地址
  oauthLogin: http://localhost:9088/login