spring:
  cloud:
    # Nacos 注册中心
    nacos:
      discovery:
        enabled: true
        register-enabled: true
#        server-addr: 192.168.30.180:8848
        server-addr: 192.168.0.10:8848
#        namespace: a6b8fdfd-14b4-4264-94fc-9d41b92a7035
        namespace: 7fbd94b1-686e-4270-b148-d50e4b2ce64c
