# 服务端口
server:
  port: 8001

# MinIO File Store
minio:
  store:
#    endpoint: http://192.168.30.180:9000
    endpoint: http://192.168.0.10:9000
    bucket: ms-example
    accessKey: minio
    secretKey: minio123
    partMaxSize: 10485760
    cleanCache:
      enabled: true
      directory: ./tmp
      cleanPeriod: 12960000
      aliveDuration: 12960000
